before_script:
  - git clone https://github.com/lorawan-team/Delta_LoRaWAN.git
  - cd De*
  - cp .env.example .env
  - composer update --quiet
  - bower update --quiet
  - php artisan key:generate
  - php artisan config:clear
#  - php artisan migrate
#  - php artisan migrate:status
  - php artisan api:routes
  - php artisan api:cache

stage:
  - build
  - test
  - deploy

variables:
  DATABASE_NAME: project_name
  DATABASE_USER: username
  DATABASE_PASSWORD: password

phpunit_API:php7.0:
  stage: test
  script:
    - vendor/bin/phpunit --enforce-time-limit --disallow-todo-tests --verbose --colors

deploy_API:
  stage:deploy
  script:
    - tar -czf file.tar.gz *